### ISSUE TITLE
GoTo(index) and autoplay enhancements

### ISSUE THREAD

**Issue by NikitaLoshchenin** [AlbanCrepel/vue-displacement-slideshow#11]
It would be great to extend the functionality:

- method of transition to a particular slide , something like `goTo(index)`

- the option of automatic slide change time(for convenience)

**Comment by AlbanCrepel** [comment]
Hi @NikitaLoshchenin , sorry to answer this late... 
The `gotTo(index)` is definitely on the todo list ! I will implement it asap.

About the second option, I prefer to let the user of the component handle it by himself (like in the example that can be found in the README).

Thank you for your interest in the development of this component !

**Comment by NikitaLoshchenin** [comment]
@AlbanCrepel 
Thanks for reply!) As for the second point, I think this option is in any case necessary if you plan to expand the functionality for example to pause the focus, reset the timer when you click on the navigation buttons or drag and drop slides. Without this functionality, developers will have difficulties with the implementation of the functional extension.

**Comment by AlbanCrepel** [comment]
Hi @NikitaLoshchenin ! I am happy to tell you that I implemented the `goTo(index)` method in the latest version (1.1.0). You can find more information in the Readme 😉
