### ISSUE TITLE
can I start with the second image?

### ISSUE THREAD

**Issue by daisukeibi** [AlbanCrepel/vue-displacement-slideshow#18]
Hi,
can I start with the second image?

thank you.

**Comment by AlbanCrepel** [comment]
Hi ! If you want to start with the second image, why not putting the second image at the first index in your array ? You can also have a look to the [different methods](https://github.com/AlbanCrepel/vue-displacement-slideshow#methods) available, maybe the `goTo(index)` method suits your needs. I hope this will help you do what you intended. If so, feel free to tell it here / close this issue.

**Comment by daisukeibi** [comment]
I want to use this component for some pages.

Tried `goTo(index) `method.
But  every page starts with the second image regardless of arguments.

It's okay because it was solved by another method.

Thank you.
