### ISSUE TITLE
Create a site for the docs

### ISSUE THREAD

**Issue by EmilienLeroy** [AlbanCrepel/vue-displacement-slideshow#20]
Hi,
I think, create a site with [vuepress](https://github.com/vuejs/vuepress) can be realy helpfull (in particular for the search function).
Most of vue libs have one 😉

**Comment by AlbanCrepel** [comment]
Hello ! Yes I have been thinking about it, and planning to do it when I'll have some time.

**Comment by EmilienLeroy** [comment]
If you want, I can make a PR with the base of the documentation which is in the README 😃

**Comment by AlbanCrepel** [comment]
I was thinking about a dedicated repo for the doc. The vuepress should be developped on this repo : [https://github.com/AlbanCrepel/vue-displacement-slideshow-doc](https://github.com/AlbanCrepel/vue-displacement-slideshow-doc)

**Comment by EmilienLeroy** [comment]
Ok, but I can't fork an empty repository. ^^
Can you put a README or something other ?
And can I use [vitepress](https://github.com/vuejs/vitepress) even though it's still under development ?

**Comment by AlbanCrepel** [comment]
Oh yeah sorry, it should be all good now : I set up the repository with vitepress 😉
