### ISSUE TITLE
Access current image index

### ISSUE THREAD

**Issue by kabugh** [AlbanCrepel/vue-displacement-slideshow#21]
Hey, first of all, I'd like to thank you for this awesome plugin!

I am trying to add text description for each image in the slideshow. Is there any way to access current image index, so I could use it so as to display appropriate text? 🔥

**Comment by AlbanCrepel** [comment]
Hi ! :wave: Thanks for your feedbacks, I really appreciate it !

One way to get the current image index is to do something like this in the `mounted` hook of your component : 
```js
this.$watch(
    () => {
        return this.$refs.displacementSlideshow.currentImage
    },
    (val) => {
        console.log(val) // the current image index, you can do whatever you want with it
    }
)
```

Given that you put `displacementSlideshow` as a name for the reference of the component, this would work (I believe this is the only way to get a data from a reference reactive).

I hope that is clear enough for you and solved your issue 😉
