### ISSUE TITLE
would it be possible to apply the transition effect on a div rather than on images?

### ISSUE THREAD

**Issue by vesper8** [AlbanCrepel/vue-displacement-slideshow#29]
I would like to apply the super cool effects to a div that contains multiple images / html content.. rather than on individual images. Would this be possible without too much hacking?

**Comment by AlbanCrepel** [comment]
Hi @vesper8, this wouldn't be possible with vue-displacement-slideshow, as it uses ThreeJs as WebGl renderer, and the images are used as textures, and you can't set a whole div as a texture. I believe this would require a custom ThreeJs development. Sorry that this library doesn't suit this need.
