### ISSUE TITLE
Camera aspect ratio

### ISSUE THREAD

**Issue by RomainFrancony** [AlbanCrepel/vue-displacement-slideshow#3]
No an issue because It doesn't seems to be broken but.

https://github.com/AlbanCrepel/vue-displacement-slideshow/blob/9070586572cfe197c63f34c842d70f59ef066724/src/VueDisplacementSlideshow.vue#L213

Shouldn't it be `this.slider` size instead of `window` ?

**Comment by AlbanCrepel** [comment]
@RomainFrancony yes you're right, I changed it in the latest version (0.1.7), thanks !
