### ISSUE TITLE
canvas transparency

### ISSUE THREAD

**Issue by fborgherodbsagency** [AlbanCrepel/vue-displacement-slideshow#41]
We tried for hours to remove the black background  of the canvas as we are using PNG images for the transitions. Any hint? we really tried every possible setting of transparency but with no luck

**Comment by AlbanCrepel** [comment]
Could you leave a reproduction link (or any bit of code) ? I am not quite sure what is the source of your issue. Is it about PNG transparency ? (from the displacement image or from the slider images ?)
You can still fix it and submit a PR if you would like, contributions are welcome.

**Comment by BraceZenith** [comment]
I have the same issue.
I'm using transparent PNGs for the slides, and I'm using regular JPG for the displacement image.
In testing with https://github.com/robin-dela/hover-effect which I assume this slider is based on, I have no problem using transparent PNGs for the slides, while using a regular JPG as the displacement image. I get a transparent background, and I can use the library over other elements, and I'm able to see them behind the canvas. In the case with this library, it seems I can't do that. So my question is, whether this is possible or not?

Thanks in advance for the answer, and for the library. This issue aside, it's still a great asset.

**Comment by AlbanCrepel** [comment]
Hey @fborgherodbsagency and @BraceZenith, I fixed this issue in the last version of the component. Sorry for the late fix... You can update to `4.0.1` and it should be fixed for you. Thanks again for reporting it ✨

**Comment by BraceZenith** [comment]
@AlbanCrepel Thank you so much. Love the library. Used it for 2 projects already.

**Comment by AlbanCrepel** [comment]
Well thanks for your feedback @BraceZenith, it's always appreciated !

If you are into markdown and knowledge base, you can check out this other project I developed : [Compiiile](https://github.com/AlbanCrepel/compiiile), that allows you to preview a folder (and sub-folders) containing markdown files and searching through all the files and build it as a website.

Once again, it's open-source and tries to contribute to the beauty of the internet 🌟 

It's totally not mandatory, but you can support my open-source work on [my ko-fi page](https://ko-fi.com/alban_crepel).
