### ISSUE TITLE
Getting require not defined errors, is it vite compatible ?

### ISSUE THREAD

**Issue by underhoney** [AlbanCrepel/vue-displacement-slideshow#42]
Uncaught ReferenceError: require is not defined
    at Proxy.images (App.vue:21:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at Object.get [as images] (runtime-core.esm-bundler.js:3488:30)
    at Proxy._sfc_render (App.vue:3:22)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)

**Comment by AlbanCrepel** [comment]
@underhoney I suppose you are looking at the [example from the Readme](https://github.com/AlbanCrepel/vue-displacement-slideshow#example). `required` worked with webpack, that was used before. You can load your images in vite by importing them, as seen in [Vite's documentation](https://vitejs.dev/guide/assets.html#static-asset-handling).

Could you confirm that it is working this way with vite ?

**Comment by underhoney** [comment]
<template>
    <vue-displacement-slideshow
            :images="images"
            displacement="displacement"
            :intensity="0.2"
            :speedIn="1.4"
            :speedOut="1.4"
            ease="expo.out"
            ref="slideshow" />
</template>

<script>
    import VueDisplacementSlideshow from "vue-displacement-slideshow";

    import imgUrl1 from './assets/images/1.png'
    import imgUrl2 from './assets/images/2.png'
    import imgUrl3 from './assets/images/3.png'
    import displacementUrl from './assets/displacement.png'


    export default {
        components: {
            VueDisplacementSlideshow,
        },
        computed: {
            images() {
                return [
                    imgUrl1,
                    imgUrl2,
                    imgUrl3
                ];
            },
            displacement() {
                return [
                    displacementUrl
                ];
            }
        },
        methods: {
            init() {
                setInterval(() => {
                    this.$refs.slideshow.next();
                }, 2000);
            }
        },
        mounted() {
            this.init();
        }
    };
</script>

**Comment by underhoney** [comment]
![snippet](https://user-images.githubusercontent.com/54747007/222497727-5fd67e03-9249-4958-819b-a61986339930.jpeg)
Does not work using the code above, probably did something wrong on my part though ..

**Comment by AlbanCrepel** [comment]
Looking at the provided code, your `displacement` computed should be `return displacementUrl` (it's not an array but a single image), and the props should be a calculated value instead of a string as it currently is : `:displacement="displacement"`. This should do the job.

**Comment by AlbanCrepel** [comment]
@underhoney to get back on the initial question, yes, this component is compatible with vite, I already used it with that bundler (that I use exclusively). Can you confirm you got it working so I can close the issue please ?
